---
- name: Install Git Server centos 7
  hosts: git01
  become: true
  vars:
    d_pwd: #password goes here

  environment: 
    EXTERNAL_URL: # 'http://git.yourdomain.com' 

  handlers:
    - name: restart sssd
      service:
        name: sssd
        state: restarted
        daemon_reload: yes

  tasks:
    - name: update system
      yum:
        name: '*'
        state: latest

    - name: install packages
      yum: 
        name: sssd,realmd,oddjob,oddjob-mkhomedir,adcli,samba-common,samba-common-tools,krb5-workstation,openldap-clients,dnf,openssh-server,postfix,policycoreutils,vim
        state: present
    
    - name: install epel
      yum: 
        name: epel-release
        state: present
      
    - name: start postfix service
      service:
        name: postfix
        enabled: yes
        state: started
    
    - name: install the latest version of python2
      dnf:
        name: python2
        state: latest

    - name: install the latest version of python3
      dnf:
        name: python3
        state: latest
    
    - name: install python pip 
      dnf: 
        name: python2-pip
        state: latest

    - name: update pip
      shell: pip2 install --upgrade pip

    - name: pip install pexpect
      shell: pip2 install pexpect
    
    - name: Copy repository file
      copy:
        src: ./gitlab-ce.repo
        dest: /etc/yum.repos.d
        owner: root
        group: root
        mode: u=rwx,g=rwx,o=rwx
    
    - name: udpate cache 
      yum: 
        update_cache: yes
    
    - name: install gitlab
      shell: EXTERNAL_URL="http://git01.yourdomain.com" yum install -y gitlab-ce
    - name: install firewall rule https
      firewalld:
        service: https
        permanent: yes
        state: enabled
        
    - name: install firewall rule http
      firewalld:
        service: http
        permanent: yes
        state: enabled

    - name: Rename Hostname
      hostname:
        name: git01
    
    - name: Check if machine is bound
      shell: /bin/bash -c "realm list | grep sssd"
      register: realmd_bound
      changed_when: false
      ignore_errors: true

    - name: Join system to AD and put the computer object in the Linux OU
      expect:
        command: /bin/bash -c "/usr/sbin/realm join --user=administrator yourdomain.com"
        responses:
          Password for *: "{{ d_pwd }}"
      when: realmd_bound|failed
    

    - name: Add ad group to sudoers
      lineinfile:
        dest: /etc/sudoers
        line: '%yourdomain\\domain\ admins ALL=(ALL) ALL'
        insertafter: '^%wheel'
      when: realmd_bound|failed

    - name: Copy file with owner and permissions
      copy:
        src: /etc/sssd/sssd.conf
        dest: /etc/sssd/sssd.conf.bkf

    - name: Change Fully Qualified Domain Requirements
      lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^use_fully_qualified_names = True'
        line: use_fully_qualified_names = False
      notify:
        - restart sssd
    - name: Add dns update
      lineinfile:
        path: /etc/sssd/sssd.conf
        line: dyndns_update = True
        create: yes
      notify:
        - restart sssd





        

